In [ ]:
import pandas as pd
df = pd.read_csv("vgchartz-2024.csv")
df.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [ ]:
df.drop('img', axis = 1, inplace = True)

In [ ]:
df.head()

,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [ ]:
miss = df.isnull().sum()
miss = miss[miss>0].sort_values(ascending = False)
miss

critic_score    57338
jp_sales        57290
na_sales        51379
pal_sales       51192
other_sales     48888
last_update     46137
total_sales     45094
release_date     7051
developer          17
dtype: int64

In [ ]:
df.drop(columns = ['last_update', 'release_date', 'developer'], axis = 1, inplace = True)

In [ ]:
df.shape

(64016, 10)

In [ ]:
df.isnull().sum().sort_values(ascending = False)

critic_score    57338
jp_sales        57290
na_sales        51379
pal_sales       51192
other_sales     48888
total_sales     45094
console             0
title               0
genre               0
publisher           0
dtype: int64

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [ ]:
df = df.dropna(subset=['total_sales'])
df['success'] = df['total_sales'].apply(lambda x:1 if x>=1.0 else 0)
df['critic_missing'] = df['critic_score'].isnull().astype(int)

/tmp/ipython-input-1111943445.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['success'] = df['total_sales'].apply(lambda x:1 if x>=1.0 else 0)
/tmp/ipython-input-1111943445.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['critic_missing'] = df['critic_score'].isnull().astype(int)

In [ ]:
iter = IterativeImputer(random_state = 42)
num_cols = ['critic_score', 'jp_sales', 'na_sales', 'pal_sales', 'other_sales']
df[num_cols] = iter.fit_transform(df[num_cols])

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
/tmp/ipython-input-4082742137.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[num_cols] = iter.fit_transform(df[num_cols])

In [ ]:
df.head()

,title,console,genre,publisher,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,success,critic_missing
0,Grand Theft Auto V,PS3,Action,Rockstar Games,9.400000,20.32,6.37,0.99,9.85,3.12,1,0
1,Grand Theft Auto V,PS4,Action,Rockstar Games,9.700000,19.39,6.06,0.60,9.71,3.02,1,0
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,9.600000,16.15,8.41,0.47,5.49,1.78,1,0
3,Grand Theft Auto V,X360,Action,Rockstar Games,11.066284,15.86,9.06,0.06,5.33,1.42,1,1
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,8.100000,15.09,6.18,0.41,6.05,2.44,1,0

In [ ]:
df_copy = df.copy()
df_copy.drop(columns = ['title', 'console', 'genre', 'publisher'], inplace = True, axis = 1)

In [ ]:
df_copy

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,success,critic_missing
0,9.400000,20.32,6.370000,0.990000,9.850000,3.12,1,0
1,9.700000,19.39,6.060000,0.600000,9.710000,3.02,1,0
2,9.600000,16.15,8.410000,0.470000,5.490000,1.78,1,0
3,11.066284,15.86,9.060000,0.060000,5.330000,1.42,1,1
4,8.100000,15.09,6.180000,0.410000,6.050000,2.44,1,0
...,...,...,...,...,...,...,...,...
18917,7.000000,0.00,0.119895,0.071080,0.000000,0.00,0,0
18918,6.400000,0.00,0.000000,0.002522,0.000000,0.00,0,0
18919,6.000000,0.00,0.000000,-0.049616,-0.007219,0.00,0,0
18920,7.009089,0.00,0.000000,0.082215,0.000000,0.00,0,1
18921,7.010401,0.00,0.000000,0.082367,0.004674,0.00,0,1

In [ ]:
df.head()

,title,console,genre,publisher,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,success,critic_missing
0,Grand Theft Auto V,PS3,Action,Rockstar Games,9.400000,20.32,6.37,0.99,9.85,3.12,1,0
1,Grand Theft Auto V,PS4,Action,Rockstar Games,9.700000,19.39,6.06,0.60,9.71,3.02,1,0
2,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,9.600000,16.15,8.41,0.47,5.49,1.78,1,0
3,Grand Theft Auto V,X360,Action,Rockstar Games,11.066284,15.86,9.06,0.06,5.33,1.42,1,1
4,Call of Duty: Black Ops 3,PS4,Shooter,Activision,8.100000,15.09,6.18,0.41,6.05,2.44,1,0

In [ ]:
df.drop(columns = ['title', 'total_sales'], axis = 1, inplace = True)

/tmp/ipython-input-298248977.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns = ['title', 'total_sales'], axis = 1, inplace = True)

In [ ]:
df.head()

,console,genre,publisher,critic_score,na_sales,jp_sales,pal_sales,other_sales,success,critic_missing
0,PS3,Action,Rockstar Games,9.400000,6.37,0.99,9.85,3.12,1,0
1,PS4,Action,Rockstar Games,9.700000,6.06,0.60,9.71,3.02,1,0
2,PS2,Action,Rockstar Games,9.600000,8.41,0.47,5.49,1.78,1,0
3,X360,Action,Rockstar Games,11.066284,9.06,0.06,5.33,1.42,1,1
4,PS4,Shooter,Activision,8.100000,6.18,0.41,6.05,2.44,1,0

In [ ]:
df['console'].isnull().sum()

np.int64(0)

In [ ]:
df.drop('publisher', axis = 1, inplace = True)

/tmp/ipython-input-3760752720.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('publisher', axis = 1, inplace = True)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [ ]:
cat_cols = ['console', 'genre']
num_cols = ['critic_score', 'na_sales', 'jp_sales', 'pal_sales', 'other_sales', 'critic_missing']
preprocess = ColumnTransformer([
    ('cat', OneHotEncoder(), cat_cols),
    ('num', StandardScaler(), num_cols)
])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier

In [ ]:
base_models = [
    ('lr', LogisticRegression(max_iter=1000)),
    ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
    ('gb', GradientBoostingClassifier(n_estimators=100, random_state=42)),
    ('svc', SVC(probability=True, kernel='rbf'))
]
meta_model = RandomForestClassifier(n_estimators = 100, random_state = 42)
stack_model = StackingClassifier(
    estimators = base_models,
    final_estimator= meta_model,
    cv = 5
)

In [ ]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline(steps = [
    ('preprocess', preprocess),
    ('model', stack_model)

])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
x = df[num_cols + cat_cols]
y = df['success']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [ ]:
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['console', 'genre']),
                                                 ('num', StandardScaler(),
                                                  ['critic_score', 'na_sales',
                                                   'jp_sales', 'pal_sales',
                                                   'other_sales',
                                                   'critic_missing'])])),
                ('model',
                 StackingClassifier(cv=5,
                                    estimators=[('lr',
                                                 LogisticRegression(max_iter=1000)),
                                                ('rf',
                                                 RandomForestClassifier(random_state=42)),
                                                ('gb',
                                                 GradientBoostingClassifier(random_state=42)),
                                                ('svc', SVC(probability=True))],
                                    final_estimator=RandomForestClassifier(random_state=42)))])

In [ ]:
y_pred = pipeline.predict(x_test)
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      3489
           1       0.99      0.94      0.96       296

    accuracy                           0.99      3785
   macro avg       0.99      0.97      0.98      3785
weighted avg       0.99      0.99      0.99      3785

0.9941875825627476